<?php

/**
 * @file
 * Code for osto_html_mails.
 */

/**
 * Implements hook_mail_alter().
 *
 * Change mail header for all html mails.
 */
function osto_html_mails_mail_alter(&$message) {
  // Check if message contains html and set header accordingly.
  if (isset($message['body'][0])) {
    $body = $message['body'][0];
    // @see https://stackoverflow.com/a/33614682.
    if (preg_match('/\/[a-z]*>/i', $body) === 1) {
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
    }
  }
}
