<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

/**
 * Implements hook_uninstall().
 */
function breadcrumbs_by_path_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'breadcrumbs_by_path_%'");
}

/**
 * Implements hook_update_N().
 */
function breadcrumbs_by_path_update_7100() {
  db_update('system')->fields(array(
    'weight' => -6
  ))
  ->condition('name', 'breadcrumbs_by_path', '=')
  ->execute();
}
