<?php 
/**
 * @file
 * This file is responsible for everything the module does. 
 */

/**
 * Implements hook_form_alter().
 */
function context_block_visibility_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form') {
    $form['visibility']['contexts'] = array(
      '#type' => 'fieldset',
      '#title' => 'Context',
      '#group' => 'visibility',
      '#weight' => 99,
      '#attached' => array(
        'js' => array(
          'vertical-tabs' => drupal_get_path('module', 'context_block_visibility') . "/context_block_visibility_vtabs.js",
        ),
      ),
    );
    $contexts = context_load();
    $options = array();
    foreach ($contexts as $cid => $context) {
      $options[$cid] = $context->name;
    }
    $default_context_options = db_query("SELECT context FROM {context_visibility_context} WHERE module = :module AND delta = :delta", array(
      ':module' => $form['module']['#value'],
      ':delta' => $form['delta']['#value'],
    ))->fetchCol();
    $form['visibility']['contexts']['context'] = array(
      '#type' => 'checkboxes',
      '#title' => 'Contexts:',
      '#options' => $options,
      '#default_value' => $default_context_options,
    );
    $form['#submit'][] = 'context_block_visibility_save_contexts';
  }
}

/**
 * Our submit handler for blocks.
 */
function context_block_visibility_save_contexts($form, $form_state) {
  $contexts = $form_state['values']['context'];
  db_delete('context_visibility_context')
    ->condition('module', $form_state['values']['module'])
    ->condition('delta', $form_state['values']['delta'])
    ->execute();
  foreach ($contexts as $context => $selected) {
    $record = array(
      'module' => $form_state['values']['module'],
      'delta' => $form_state['values']['delta'],
      'context' => $selected,
    );
    if ($selected !== 0) {
      drupal_write_record('context_visibility_context', $record);
    }
  }
}

/**
 * Implements hook_block_list_alter().
 */
function context_block_visibility_block_list_alter(&$blocks) {
  $context = context_get();
  $context = isset($context['context']) ? $context['context'] : array();

  // Build an array of roles for each block.
  $block_contexts = array();
  $result = db_query('SELECT module, delta, context FROM {context_visibility_context}');
  foreach ($result as $record) {
    $block_contexts[$record->module][$record->delta][] = $record->context;
  }

  foreach ($blocks as $key => $block) {
    // If a block has no contexts associated, it is displayed for every role.
    // For blocks with contexts associated, if none of the contexts matches
    // the settings from this block, remove it from the block list.
    if (isset($block_contexts[$block->module][$block->delta]) && !array_intersect($block_contexts[$block->module][$block->delta], array_keys($context))) {
      // No match.
      unset($blocks[$key]);
      continue;
    }
  }
}
